### ISSUE TITLE
urfave-cli changes are breaking builds

### ISSUE THREAD

**Issue by calthomson** [anubhavmishra/envoy-consul-sds#3]
Recent changes to a dependency of this project, `urfave-cli`, are causing an error in this project:

```

# github.com/anubhavmishra/envoy-consul-sds
--
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:51:14: cannot use cli.IntFlag literal (type cli.IntFlag) as type cli.Flag in array or slice literal:
  | cli.IntFlag does not implement cli.Flag (Apply method has pointer receiver)
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:56:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
  | cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:61:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
  | cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:66:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
  | cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:70:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
  | cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
  | src/github.com/anubhavmishra/envoy-consul-sds/main.go:75:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
  | cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)

```

Here is an example of this issue someone posted in the `urfave/cli` project: https://github.com/urfave/cli/issues/926

Seems like it's going to be broken for projects that don't have go modules. Can we add go modules to this project?

**Comment by coilysiren** [comment]
@calthomson in case you haven't seen it already, here's a PR where someone fixes this https://github.com/purpleidea/mgmt/pull/571

@calthomson, @anubhavmishra if / when you fix the problem here, can ya cc me? I want to make sure I know how people are fixing this 🙏

**Comment by calthomson** [comment]
@lynncyrin 

I forked the repo, added go modules, and updated the code to work with the latest urfave/cli changes. Created a PR in case you're interested: https://github.com/anubhavmishra/envoy-consul-sds/pull/4

**Comment by anubhavmishra** [comment]
@calthomson Thank you so much for the pull request. I will be merging it soon. 👍🏽

**Comment by anubhavmishra** [comment]
Merged: https://github.com/anubhavmishra/envoy-consul-sds/pull/4 so I am closing this issue. Once again, thank you @calthomson. 🎉
